### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by scottbelden** [bitly/statsdaemon#100]
We noticed that the fix to allow timers to use floats is in `master` but not in the `0.7.1` release. It looks like the last release was from 2015.

Are there any plans to make a new release any time soon?

Thanks!

**Comment by clayg** [comment]
I'm getting messages like:

```
2020/06/09 19:39:28 ERROR: failed to ParseUint 9.32288169861 - strconv.ParseUint: parsing "9.32288169861": invalid syntax
```

I'm using https://github.com/DandyDev/graphite-stack-ansible-vagrant which pulls in statsdaemon using this URL

https://github.com/bitly/statsdaemon/releases/download/v0.7.1/statsdaemon-0.7.1.linux-amd64.go1.4.2.tar.gz

@scottbelden is the issue you described that's fixed on master?

**Comment by scottbelden** [comment]
@clayg That is the error I'm getting as well. I assume it's fixed on `master` since the README makes that claim, but I haven't tried building from `master` and verifying.

**Comment by jehiah** [comment]
@scottbelden @clayg Thanks for bringing this to our attention, We'll get a release out shortly.
