### ISSUE TITLE
No support for float counters or gauges

### ISSUE THREAD

**Issue by drawks** [bitly/statsdaemon#59]
the etsy reference implementation supports floats for gauges and counters, if statsdaemon doesn't it should be made clear in the documentation somewhere since this is deviation from the protocol. I mean it is atypical for clients to send floats for counters, but for gauges it often makes sense. Either way I think doing only ints is probably more performant, but should be well documented.

**Comment by markrechler** [comment]
@drawks Thanks for the suggestion. Added a note to the readme.
