### ISSUE TITLE
New release with Go > 1.5.1

### ISSUE THREAD

**Issue by nordicdyno** [bitly/statsdaemon#72]
Is it possible to release new binary with better GC under the hood?

**Comment by mreiferson** [comment]
this sounds reasonable :+1:

**Comment by markrechler** [comment]
Binaries built against go1.5.1 have been attached for the [v0.7.1](https://github.com/bitly/statsdaemon/releases/tag/v0.7.1) release. Thanks for the suggestion @nordicdyno.
