### ISSUE TITLE
StatsD supports decimal values, this fork doesn't.

### ISSUE THREAD

**Issue by AlejandroRivera** [bitly/statsdaemon#76]
For example Gauges allow for decimal values:
https://github.com/etsy/statsd/blob/master/stats.js#L262-L264

**Comment by ploxiln** [comment]
see #68 #71

**Comment by AlejandroRivera** [comment]
Thanks for the links @ploxiln. For some reason i forgot to take a look at the open PRs, but i guess it can't hurt to have this reported as an issue, right? :)

Anyway, do you know who's calling the shots here? Based on the timestamp of those PRs (May 2015), is  it safe to assume this port won't include these features any time soon, right?

**Comment by ploxiln** [comment]
Now fixed in master :)
