### ISSUE TITLE
floats are supported now, but README says no?

### ISSUE THREAD

**Issue by joemiller** [bitly/statsdaemon#88]
The README on master branch indicates only integers are supported but I see some closed PRs and commits (such as this one: https://github.com/bitly/statsdaemon/commit/150dbf42eec31cdbb386a823c571888ea1cdb815) that would indicate floats are supported now as well. I just wanted to confirm this?  I'm happy to send a PR to remove or update the README if so =)

**Comment by ploxiln** [comment]
Yup, looks like README was missed in #77, go ahead :)
